site_name: vector
site_url: https://goessl.github.io/vector/
site_author: Sebastian Gössl
site_description: An infinite-dimensional vector Python package.

repo_name: goessl/vector
repo_url: https://github.com/goessl/vector

copyright: Copyright &copy; 2022 - 2025 Sebastian Gössl

nav:
  - Home: index.md
  - Functional: functional.md
  - Object-oriented: objectoriented.md
  - Parallelised: parallelised.md
  - Multiaxis: multiaxis.md
  - Design: design.md

theme:
  name: readthedocs
  logo: logo.png
